autocompile tweaks.

diff --git a/bones-autocompile b/bones-autocompile
--- a/bones-autocompile
+++ b/bones-autocompile
@@ -1,9 +1,15 @@
 #!/bin/sh
 ### autocompile-script for bones
 #
-# usage: bones-autocompile FILENAME
+# usage: bones-autocompile [-h] FILENAME ARGUMENT ...
 
 set -e
+
+case "$1" in
+    -h|-help|--help)
+	echo "usage: bones-autocompile [-h] FILENAME ARGUMENT ..."
+	exit;;
+esac
 
 filename=$1
 shift
@@ -20,8 +26,8 @@ fi
 hash=`md5sum "$filename" | sed -e 's/^\([a-f0-9]\+\).*$/\1/'`
 
 if test -z "$hash"; then
-  echo "invalid filename: $filename" >2
-  exit 1
+    echo "invalid filename: $filename" >2
+    exit 1
 fi
 
 if test -x "${cachedir}/${hash}"; then
